name: Generate Burndown Chart

on:
  schedule:
    - cron: '0 0 * * *' # Este cron job se ejecutará diariamente a la medianoche
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  generate-burndown-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas PyGithub

    - name: Generate burndown chart
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python generate_burndown.py

    - name: Upload burndown chart
      uses: actions/upload-artifact@v2
      with:
        name: burndown-chart
        path: burndown_chart.png
